### ISSUE TITLE
Extremely low fps

### ISSUE THREAD

**Issue by Theronguard** [slayer6409/Emergency-Dice-Updated#7] opened 2024-11-02 11:02 UTC
Hi, the original mod creator here. Thanks for all the good dev work. I love the highly customizable config.

I wanted to try this mod out, because I saw that it is frequently updated and has new effects so why not try it. Sadly though I noticed an extreme fps drop when playing with my friends. I isolated a lot of mods and it came down to **Emergency dice updated**. Disabling it fixed all the fps issues.

- The fps drop to about 5-10 fps
- **This doesn't happen on the host**, only on the connecting clients.
- I have an RX 6700 xt + i5 12400f while my friend has Gtx 1050 ti and i5 7 gen.
I didn't have an fps indicator so the fps could have dropped for me when i was a client but I just didnt notice, but hers definitely did.
- The fps drop doesn't occur in the ship before landing on the planet. When the landing phase begins, the fps drop instantly. Without the mod, everything runs smoothly for her. (tested on assurance, offense and experimentation - happens on all of them)

Do you have any idea what could be the cause?
I'll try to look around your code to find anything but I wanted to report this first.
If I had to guess, it is probably something in a clients update loop.

Also seeing that you maintain this mod very well I'll link to it on my repo :) I don't have as much time to work on it sadly. I wanted to rewrite it from scratch because I hate the way I coded it, but I'll just link to your mod.
Have a nice day!

**Comment by slayer6409** [comment] 2024-11-02 11:11
I believe I know what the issue is, I just have to wait until I'm off work, but I broke the gambler accidentally. I have it mostly fixed (I think, I'm still very new to modding lol), but there were still a few issues with it that I need to fix before I could push the update, but it should be out sometime today!
I really enjoyed your mod and just am glad people like some of my changes! 
Thank you for creating your mod! It has been fun learning to make mods by maintaining this!

**Comment by Qing-Ba** [comment] 2024-11-09 16:36
When I use this mod as the host, my friend's frame rate is capped at 30 FPS.

**Comment by slayer6409** [comment] 2024-11-09 16:57
It is recommended to revert to 1.5.13
I am currently trying to figure out what is causing the issue, but that version is the last version that has stable frames

**Comment by slayer6409** [comment] 2024-11-09 23:33
It seems to be fixed now on the newest update 
I did a lot of changes that _should_ fix the issues

**Closed** 2024-11-11 07:23 UTC
